- name: app setup
  ansible.builtin.import_role:
    name: comman
    tasks_from: app-setup

- name: java setup
  ansible.builtin.import_role:
    name: comman
    tasks_from: java-setup

- name: mysql setup
  ansible.builtin.import_role:
    name: comman
    tasks_from: mysql-setup

- name: systemd setup
  ansible.builtin.import_role:
    name: comman
    tasks_from: systemd 