- name: app setup
  ansible.builtin.import_role:
    name: comman
    tasks_from: app-setup

- name: go
  ansible.builtin.import_role:
    name: comman
    tasks_from: go-setup

- name: system start
  ansible.builtin.import_role:
    name: comman
    tasks_from: systemd