- name: disable and enable node-js
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install node-js
  ansible.builtin.package:
    name: nodejs
    state: present  

- name: Add the roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent    

- name: Create app directory 
  ansible.builtin.file:
    path: /app
    state: directory

- name: download url
  ansible.builtin.uri:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp
    

- name: Extract 
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes

- name: install npm
  ansible.builtin.command: npm install
  args: 
    chdir: /app

- name: Copy catalogue service file 
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
        
- name: deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  
- name: Copy mongo repo 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
    
- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present  

- name: get the categories count
  ansible.builtin.command:  mongo --host mongodb.jaya123.shop --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count  

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.jaya123.shop < /app/schema/catalogue.js
  when: product_count.stdout == "0" # keep double quotes

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes

